# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ncella <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/07 15:07:09 by ncella            #+#    #+#              #
#    Updated: 2017/11/07 15:07:11 by ncella           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	@gcc -c ft_display_file.c
	@gcc ft_display_file.o -o ft_display_file

clean:
	@/bin/rm -f ft_display_file.o

fclean: clean
	@/bin/rm -f ft_display_file

re: fclean all